name: Build

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac
            build_cmd: build:mac
          - os: windows-latest
            platform: win
            build_cmd: build:win
          - os: ubuntu-latest
            platform: linux
            build_cmd: build:linux

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run typecheck

      - name: Build Electron app
        run: npm run ${{ matrix.build_cmd }}
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.platform }}-build-${{ github.sha }}
          path: |
            dist/**/*
            !dist/**/*.yml
            !dist/**/builder-debug.yml
            !dist/**/*.yaml
            !dist/**/builder-effective-config.yaml
          retention-days: 1
